<a href="https://colab.research.google.com/github/MirandaCarou/Research-Intership-Memory/blob/main/Qutrits_neutrinoQuForge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
!pip install quforge

In [2]:
# # First, we import the libaries
# import quforge.quforge as qf
# from quforge.quforge import State as State
import sys
sys.path.append('../')
import quforge.quforge as qf
from quforge.quforge import *

In [3]:
import matplotlib.pyplot as plt
from IPython.display import display, Math, Latex
import numpy as np


**Basic Gates**



```
State(dits, dim=2, device='cpu')
density_matrix(state)
partial_trace(state, index=[0], dim=2, wires=1)
projector(index, dim)
measure(state=None, index=[0], shots=1, dim=2, wires=1)
project(state, index=[0], dim=2)
mean(state, observable='Z', index=0)

eye(dim, device='cpu', sparse=False) # Create a sparse identity matrix
zeros(m,n, device='cpu')
ones(m,n, device='cpu')
kron(matrix1, matrix2, sparse=False) # Tensor product of dense or sparse matrix
base(D, device='cpu')
fidelity(state1, state2)
argmax(x)
mean(x)

Linear(nn.Linear)
Sequential(nn.Sequential)
ReLU(nn.ReLU)
Sigmoid(nn.Sigmoid)
Tanh(nn.Tanh)
LeakyReLU(nn.LeakyReLU)
Softmax(nn.Softmax)
```



**Quantum Circuit for qudits using QuForge**.

    The Circuit class allows users to dynamically add various quantum gates to construct a quantum circuit for qudit systems. It supports a wide range of gates, including single, multi-qudit, and custom gates. The class provides methods to add specific gates as well as a general interface for adding custom gates.

    **Details:**

    This class facilitates the construction of quantum circuits by allowing the sequential addition of gates. The circuit is represented as a sequence of quantum operations (gates) that act on qudit states.

    Args:
        dim (int): The dimension of the qudits. Default is 2.
        wires (int): The total number of qudits (wires) in the circuit. Default is 1.
        device (str): The device to perform the computations on. Default is 'cpu'.
        sparse (bool): Whether to use sparse matrix representations for the gates. Default is False.

    Attributes:
        dim (int): The dimension of the qudits.
        wires (int): The number of qudits in the circuit.
        device (str): The device for computations ('cpu' or 'cuda').
        circuit (nn.Sequential): A sequential container for holding the quantum gates.
        sparse (bool): Whether to use sparse matrices in the gates.

    Methods:
        add(module, **kwargs): Dynamically add a gate module to the circuit.
        add_gate(gate, **kwargs): Add a specific gate instance to the circuit.
        H(**kwargs): Add a Hadamard gate to the circuit.
        RX(**kwargs): Add a rotation-X gate to the circuit.
        RY(**kwargs): Add a rotation-Y gate to the circuit.
        RZ(**kwargs): Add a rotation-Z gate to the circuit.
        X(**kwargs): Add a Pauli-X gate to the circuit.
        Y(**kwargs): Add a Pauli-Y gate to the circuit.
        Z(**kwargs): Add a Pauli-Z gate to the circuit.
        CNOT(**kwargs): Add a controlled-NOT gate to the circuit.
        SWAP(**kwargs): Add a SWAP gate to the circuit.
        CZ(**kwargs): Add a controlled-Z gate to the circuit.
        CCNOT(**kwargs): Add a Toffoli (CCNOT) gate to the circuit.
        MCX(**kwargs): Add a multi-controlled-X gate to the circuit.
        CRX(**kwargs): Add a controlled rotation-X gate to the circuit.
        CRY(**kwargs): Add a controlled rotation-Y gate to the circuit.
        CRZ(**kwargs): Add a controlled rotation-Z gate to the circuit.
        Custom(**kwargs): Add a custom gate to the circuit.

    Examples:
        >>> import quforge.quforge as qf
        >>> circuit = qf.Circuit(dim=2, wires=3, device='cpu')
        >>> circuit.H(index=[0])
        >>> circuit.CNOT(index=[0, 1])
        >>> state = qf.State('0-0-0')
        >>> result = circuit(state)
        >>> print(result)
    """

class **CustomGate**(nn.Module):

    Custom Quantum Gate for qudits.

    The CustomGate class allows users to define and apply a custom quantum gate to a specific qudit in a multi-qudit system. This gate can be any user-defined matrix, making it highly flexible for custom operations.

    **Details:**

    This gate applies a custom unitary matrix :math:`M` to the specified qudit while leaving other qudits unaffected by applying the identity operation to them.

    Args:
        M (torch.Tensor): The custom matrix to be applied as the gate.
        dim (int): The dimension of the qudits. Default is 2.
        wires (int): The total number of qudits (wires) in the circuit. Default is 1.
        index (int): The index of the qudit to which the custom gate is applied. Default is 0.
        device (str): The device to perform the computations on. Default is 'cpu'.

    Attributes:
        M (torch.Tensor): The custom matrix for the gate.
        dim (int): The dimension of the qudits.
        index (int): The index of the qudit on which the custom gate operates.
        wires (int): The total number of qudits in the system.
        device (str): The device for computations ('cpu' or 'cuda').

    Examples:
        >>> import quforge.quforge as qf
        >>> custom_matrix = torch.tensor([[0, 1], [1, 0]])  # Example custom matrix
        >>> gate = qf.CustomGate(M=custom_matrix, dim=2, index=0, wires=2)
        >>> state = qf.State('00')
        >>> result = gate(state)
        >>> print(result)
    """

In [4]:
def print_matrix(matrix):
    """Prints a matrix using LaTeX formatting."""

    latex_code = "\\begin{bmatrix}\n"
    for row in matrix:
        latex_code += " & ".join(map(str, row)) + " \\\\\n"  # Format each row
    latex_code += "\\end{bmatrix}"

    display(Math(latex_code))  # Display using IPython's Math function

def pmns_matrix(theta12, theta23, theta13, delta):
    """Genera la matriz PMNS con los parámetros dados."""
    c12, s12 = np.cos(theta12), np.sin(theta12)
    c23, s23 = np.cos(theta23), np.sin(theta23)
    c13, s13 = np.cos(theta13), np.sin(theta13)

    e_minus_idelta = np.exp(-1j * delta)
    e_plus_idelta = np.exp(1j * delta)

    return np.array([
        [c12 * c13, s12 * c13, s13 * e_minus_idelta],
        [-s12 * c23 - c12 * s23 * s13 * e_plus_idelta,
         c12 * c23 - s12 * s23 * s13 * e_plus_idelta,
         s23 * c13],
        [s12 * s23 - c12 * c23 * s13 * e_plus_idelta,
         -c12 * s23 - s12 * c23 * s13 * e_plus_idelta,
         c23 * c13]
    ])

# Parámetros de ejemplo
theta12 = np.pi / 4
theta23 = np.pi / 6
theta13 = np.pi / 8
delta = np.pi / 2

# Crear matriz PMNS
U_pmns = pmns_matrix(theta12, theta23, theta13, delta)

print("Matriz PMNS:")
print_matrix(U_pmns)

U_pmns[0, 0]

Matriz PMNS:


<IPython.core.display.Math object>

(0.6532814824381883+0j)

In [5]:
def gell_mann_matrices():
    gm1 = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 0]], dtype=complex)
    gm2 = np.array([[0, -1j, 0], [1j, 0, 0], [0, 0, 0]], dtype=complex)
    gm3 = np.array([[1, 0, 0], [0, -1, 0], [0, 0, 0]], dtype=complex)
    gm4 = np.array([[0, 0, 1], [0, 0, 0], [1, 0, 0]], dtype=complex)
    gm5 = np.array([[0, 0, -1j], [0, 0, 0], [1j, 0, 0]], dtype=complex)
    gm6 = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0]], dtype=complex)
    gm7 = np.array([[0, 0, 0], [0, 0, -1j], [0, 1j, 0]], dtype=complex)
    gm8 = np.array([[1 / np.sqrt(3), 0, 0], [0, 1 / np.sqrt(3), 0], [0, 0, -2 / np.sqrt(3)]], dtype=complex)

    return [gm1, gm2, gm3, gm4, gm5, gm6, gm7, gm8]

In [6]:
#Define iniciala state
def neutrino_state(theta, phi, eta, xi1, xi2):
    alpha = np.sin(theta) * np.cos(phi) * np.exp(1j * xi1)
    beta = np.sin(theta)* np.sin(phi) * np.exp(1j * xi2)
    gamma = np.cos(theta)
    return np.array([alpha, beta, gamma])

In [7]:
def evolve_state(state, delta_m2_ij, L, E):
    if len(delta_m2_ij) != len(state) - 1:
        raise ValueError("El tamaño de delta_m2_ij debe ser igual al número de diferencias de masas del estado (3 componentes => 2 diferencias de masa).")

    # Crear un array de fases con longitud igual al estado
    phases = np.ones(len(state), dtype=complex)
    for i in range(len(delta_m2_ij)):
        phases[i] = np.exp(-1j * delta_m2_ij[i] * L / (2 * E))

    # Aplicar las fases al estado
    evolved_state = state * phases
    # Normalizar el estado
    norm = np.linalg.norm(evolved_state)
    if not np.isclose(norm, 1):
        evolved_state /= norm

    return evolved_state


In [15]:
def neutrinos_circuit(state1, state2, dim, wires , device):
    circuit = qf.Circuit(dim=dim, wires=wires, device=device)

    circuit.H(index=[0])
    circuit.H(index=[1])
    circuit.CNOT(index=[0, 1])

    return circuit



In [10]:
def reduced_density_matrix(rho, qutrit_index):
    dim = 3
    reduced_matrix = np.zeros((dim, dim), dtype=complex)

    if qutrit_index == 1:
        # Trace over the second qutrit
        for i in range(dim):
            for j in range(dim):
                for k in range(dim):
                    reduced_matrix[i, j] += rho[i * dim + k, j * dim + k]
    elif qutrit_index == 2:
        # Trace over the first qutrit
        for i in range(dim):
            for j in range(dim):
                for k in range(dim):
                    reduced_matrix[i, j] += rho[k * dim + i, k * dim + j]
    else:
        raise ValueError("qutrit_index must be 1 or 2. Received: {}".format(qutrit_index))

    return reduced_matrix

"We calculate the entropy of mixing of the mixed state ρ using the formula ..."

**Fórmula**

$$E(\rho) = -\sum_{i} x_i \log_3(x_i)$$

In [11]:
def entropy_of_mixing(rho):
    eigenvalues = np.linalg.eigvalsh(rho)
    print(eigenvalues)
    eigenvalues = eigenvalues[eigenvalues > 1e-10]
    entropy = -np.sum(eigenvalues * np.log(eigenvalues) / np.log(3))

    return entropy

In [12]:
def generalized_concurrence(rho):
    # Ensure rho is a valid density matrix
    assert np.allclose(rho, rho.conj().T), "Input matrix must be Hermitian."
    assert np.isclose(np.trace(rho), 1.0), "Input matrix must have trace 1."

    # 0_3 matrix
    o_3_matrix = np.array([[0, -1j, 1j], [1j, 0, -1j], [-1j, 1j, 0]], dtype=complex)

    # Compute the spin-flip operation: tilde_rho = (o_3_matrix ⊗ o_3_matrix) rho* (o_3_matrix ⊗ o_3_matrix)
    rho_conj = np.conjugate(rho)
    sigma_y_tensor = np.kron(o_3_matrix, o_3_matrix)
    tilde_rho = sigma_y_tensor @ rho_conj @ sigma_y_tensor

    # Compute the product rho * tilde_rho
    product = rho @ tilde_rho

    # Compute the eigenvalues of the product
    eigenvalues = np.linalg.eigvals(product)

    # Sort eigenvalues in descending order and clip negative values (due to numerical errors)
    eigenvalues = np.sort(eigenvalues)[::-1]
    eigenvalues = np.clip(eigenvalues, 0, None)

    # Calculate the generalized concurrence
    concurrence = max(0, np.sqrt(eigenvalues[0]) - sum(np.sqrt(eigenvalues[1:])))

    return concurrence

In [25]:
dim = 3
wires = 2
device = 'cpu'

params1 = [np.pi / 2, 2*np.pi / 6, 3*np.pi / 2, 0, np.pi / 2]
params2 = [np.pi / 6, np.pi / 4, np.pi / 3, np.pi / 2, 0]
# Diferencias de masas al cuadrado y parámetros de evolución
delta_m2_ij = np.array([2.4e-3, 7.5e-5])  # Diferencias de masas al cuadrado en eV^2
L = 100  # Distancia recorrida en km
E = 1  # Energía del neutrino en GeV


# Estado inicial
state1 = neutrino_state(*params1)
state2 = neutrino_state(*params2)

print(torch.tensor(state1, dtype=torch.complex64, device=device))

# Evolución temporal
state1_evo = evolve_state(state1, delta_m2_ij, L, E)
state2_evo = evolve_state(state2, delta_m2_ij, L, E)



circuit = neutrinos_circuit(state1_evo, state2_evo, dim=dim, wires=wires, device=device)
tensor_state1_evo = torch.tensor(state1_evo, dtype=torch.complex64, device=device)
tensor_state2_evo = torch.tensor(state2_evo, dtype=torch.complex64, device=device)
initial_state = qf.kron(tensor_state1_evo, tensor_state2_evo)

state_vector = circuit(initial_state)

print("Estado completo del sistema de dos qutrits:")
print(state_vector)

print("Matriz densidad")
rho = np.outer(np.asarray(state_vector), np.asarray(np.conj(state_vector)))
print_matrix(rho.real)

tensor([5.0000e-01+0.0000j, 5.3029e-17+0.8660j, 6.1232e-17+0.0000j])
Estado completo del sistema de dos qutrits:
tensor([ 0.1162+0.3973j, -0.0696-0.1675j, -0.3085-0.0203j,  0.1783+0.0252j,
        -0.0502-0.2359j,  0.0331+0.1003j, -0.2502+0.0553j, -0.1045+0.4240j,
         0.5814-0.0634j])
Matriz densidad


<IPython.core.display.Math object>

In [26]:
print()
print(rho.shape)
# Matrices de densidad reducida
# Qutrit 1 ----------------------
reduced_rho_matrix_qutrit1 = reduced_density_matrix(rho, 1)
print("\nMatriz de densidad reducida del Qutrit 1:")
print()
print_matrix(reduced_rho_matrix_qutrit1.real)
print()
# Qutrit 2 ----------------------
reduced_rho_matrix_qutrit2 = reduced_density_matrix(rho, 2)
print("\nMatriz de densidad reducida del Qutrit 2:")
print()
print_matrix(reduced_rho_matrix_qutrit2.real)
print()


# Qutrit 1 -------------------------------------------------
# Entropía de mezcla
entropy_qutrit1 = entropy_of_mixing(reduced_rho_matrix_qutrit1)
print("\nEntropía de mezcla del Qutrit 1:")
print()
print(entropy_qutrit1.real)
print()
# Qutrit 2 -------------------------------------------------
entropy_qutrit2 = entropy_of_mixing(reduced_rho_matrix_qutrit2)
print("\nEntropía de mezcla del Qutrit 2:")
print()
print(entropy_qutrit2.real)
print()
# Concurrencia Generalizada
concurrence_value = generalized_concurrence(rho)
print("\nConcurrencia Generalizada:")
print(concurrence_value)
print()


(9, 9)

Matriz de densidad reducida del Qutrit 1:



<IPython.core.display.Math object>



Matriz de densidad reducida del Qutrit 2:



<IPython.core.display.Math object>


[0.04864655 0.14779059 0.80356302]

Entropía de mezcla del Qutrit 1:

0.5510365320048556

[0.04864654 0.1477906  0.80356303]

Entropía de mezcla del Qutrit 2:

0.5510365111508502


Concurrencia Generalizada:
(0.45927943454897735+3.507262697626458e-09j)

